name: Update Commit Hash

on:
  push:
    branches:
      - main

jobs:
  update_commit_hash:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get commit hash
        run: echo "::set-env name=COMMIT_HASH::$(git rev-parse --short HEAD)"

      - name: Update commit hash file
        run: |
          echo "'${{ steps.get_commit_hash.outputs.COMMIT_HASH }}'" > commit_hash.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add commit_hash.txt
          git commit -m "Update commit hash"
          git push
