name: Update Commit Hash

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit hash
        id: commit_hash
        run: echo "::set-output name=commit_hash::$(git rev-parse --short HEAD)"

      - name: Update commit hash
        run: echo "${{ steps.commit_hash.outputs.commit_hash }}" > commit_hash.txt

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update commit hash
          commit_options: '--author "GitHub Action <noreply@github.com>"'
          commit_files: |
            commit_hash.txt
          git_user_name: GitHub Action
          git_user_email: action@github.com
          branch: main
