name: tag-commit

on:
  push:
    branches:
      - main

jobs:
  tag_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get commit hash
        run: echo "::set-env name=COMMIT_HASH::$(git rev-parse --short HEAD)"
      - name: Update commit hash file
        run: sed -i "s/^.*$/'${{ env.COMMIT_HASH }}'/" commit_hash.txt
      - name: Commit and tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Tag commit with current commit hash" -a
          git tag ${{ env.COMMIT_HASH }}
          git push --follow-tags
